# Generated by Django 2.2.2 on 2019-08-07 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0012_collection_permitted_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.ImageField(upload_to='data/data'),
        ),
    ]
